# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0

    ldflags:
      - -X 'github.com/gelleson/assistant/internal/cmd.Version={{.Version}}'
      - -X 'github.com/gelleson/assistant/internal/cmd.Commit={{.ShortCommit}} '
      - -X 'github.com/gelleson/assistant/internal/cmd.BuildTime={{.Date}} '
    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
