language: go
sudo: false

go_import_path: github.com/gelleson/assistant
env:
  global:
    - TEST_TIMEOUT_SCALE=10
    - GO111MODULE=on
go:
  - 1.14.x
  - master

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-pro
