language: go
sudo: false

go_import_path: github.com/gelleson/assistant
env:
  global:
    - TEST_TIMEOUT_SCALE=10
    - GO111MODULE=on
go:
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - master

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-pro


deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    github_token: "$GITHUB_TOKEN"
    verbose: true
    on:
      tags: true
      branch: release
      condition: $TRAVIS_OS_NAME = linux
